version: '3'

services:
  postgres:
    image: 'postgres:11.5'
    environment:
      - 'POSTGRES_DB=ms-sales-and-stock'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin|'
    expose:
      - '5439'
    ports:
      - '5439:5432'
